### ISSUE TITLE
Event page layout

### ISSUE THREAD

**Issue by cosden** [vsoch/usrse.github.io#10]
I like the event page layout, and the categorization approach, but it does lose the chronological view. Perhaps the calendar is sufficient for this. Still, I think this is a good issue for discussion - what should the event page look like.

**Comment by mtbc** [comment]
I'd be all for where and when to be far more prominent, they're principal criteria for me in focusing attention.

**Comment by vsoch** [comment]
@exoticDFT any updates, or do you need any help?

**Comment by exoticDFT** [comment]
- Keep the boxes as "cards", but make them smaller.
- One card per row?
- Make cards clickable
- Only include upcoming events on the main events page
- Add date to top right (right-justified) of cards

**Comment by exoticDFT** [comment]
I believe I have everything mentioned above done for this issue. Here's a quick screenshot of the only event we have upcoming, with the new layout of course. Followed by a screenshot of what the page would look like if there are more events (I removed the expires check.)

![image](https://user-images.githubusercontent.com/18316938/131452455-f28bc328-aee7-4b6e-87af-4c80782d4d0c.png)

![image](https://user-images.githubusercontent.com/18316938/131453366-12caf0a7-a2e1-4c2a-a02a-76488492b573.png)


I also have some code to do it in an article style. I can share that if we would prefer to do that instead of cards (it iscomparable to the news page layout.)

**Comment by vsoch** [comment]
omg this looks gorgeous! I haven't previewed/reviewed it live yet, but will tomorrow (err later today when I wake up). The cards was such a cool idea!

**Comment by vsoch** [comment]
@exoticDFT do you want to PR to review/preview? I just realized this was commented in an issue (I assumed it was a PR in my tired state, lol).

**Comment by exoticDFT** [comment]
@vsoch Just opened the PR. Was partially waiting to see if you all thought the new design of the cards was good before I officially opened the PR. Glad you like the new design 😄

**Comment by vsoch** [comment]
I looooves it! Will take a look soon with some comments and feedback.
