### ISSUE TITLE
DEI Mission Statement Menu Highlight

### ISSUE THREAD

**Issue by cosden** [vsoch/usrse.github.io#111]
When actively browsing to the page, the DEI Mission Statement menu stays highlighted blue. It seems to be the only such item/page that behaves this way. It's not a big deal. I actually like the feature and would vote to have it be the default for other pages as it reminds you where you are.

![image](https://user-images.githubusercontent.com/5824618/134708687-b1c641d4-c40c-40e1-b6de-281a8b12d96b.png)

**Comment by cmaimone** [comment]
I had a similar (but maybe different?? IDK) thing happen.  I went to Resources > RSE Resources using the top menu.  Then the menu released.  Then when I did the browser back button to the main page, the menu opened again and had RSE Resources highlighted.  My mouse wasn't near the menu -- it was on the back button.  Seems weird

**Comment by cmaimone** [comment]
^ happens with other pages too -- when you go back, the menu opens again

**Comment by cosden** [comment]
Missing in page markdown front matter at top:
menubar: about
menubar_toc: true

https://jekyllrb.com/docs/front-matter/

**Comment by prashantkr006** [comment]
@vsoch would you like me to change that bug into the feature and add it as a default for other pages too,I can do it if you will assign it to me?

**Comment by vsoch** [comment]
@prashantkr006 happy to assign you (and thank you!) I think as @cosden pointed out, the fix is fairly easy - the side menu is missing from the top of the DEI markdown file, so the site thinks it's a separate page. So the quick fix would be to add it (which I suspect would remove the highlighting) or if you really like the feature, to have it be done consistently for all pages of this style (and then you'd want to find the style / jekyll syntax that triggers it to do that). I'd also say if we do that, I think it would look nice to match the golden yellow in the top right instead of that blue green.

Assigning you @prashantkr006  - please take the freedom to decide which approach you like, depending on what you are able to figure out.

**Comment by vsoch** [comment]
Many of the drop down menus (about included) have a submenu that is defined, and it's included as @cosden showed in the front end matter. So I think we'd want to be consistent and have the highlight on any dropdown where there are multiple choices, and the user could click and then be confused about which page they are on.

**Comment by vsoch** [comment]
More specifically:
 - About
 - Getting Involved
 - News
 
We can do those to start.

**Comment by prashantkr006** [comment]
okay, I'm working on it !!

**Comment by vsoch** [comment]
Awesome! And I'm going to bed soon, so no rush over here - the soonest I could review is tomorrow. Looking forward to it!

**Comment by mtbc** [comment]
When I build locally, I usually start in a Python virtual environment and do `bundle install` and it builds a bunch of stuff for me. I wonder if you also need that `bundle install`? I'm just guessing here until somebody more knowledgeable comes along.

**Comment by prashantkr006** [comment]
@mtbc nope your comment is not irrelevant at all and yes you are right I was trying to do `bundle install` what steps did you follow can you mentionn it to me ? Thankyou!

**Comment by vsoch** [comment]
@prashantkr006 to keep you in the loop - this site is downstream from our main site at https://github.com/USRSE/usrse.github.io. We are planning to transfer the master branch here to main over there to deploy this site to https://us-rse.org. So if you get your PR in before that, I'm happy to review here and do before the updated site is live. If the deploy comes before you are done your work, I've created a sibling issue to follow this one at https://github.com/USRSE/usrse.github.io/issues/514. The commit history for the new site will eventually be the same as here so there shouldn't be any issue with adding your work either way! I'll leave this issue open since you are actively working on it.

**Comment by prashantkr006** [comment]
okay thanks for your kind gesture! @vsoch I'm working on it and will try to PR asap!
