### ISSUE TITLE
Expired Events

### ISSUE THREAD

**Issue by cosden** [vsoch/usrse.github.io#9]
The new events page displays expired events alongside upcoming ones. 

I don't know what the right approach is (a separate past events page, or a toggle switch to show old events, etc) but I don't think they should, by default, be displayed on the main events page. An easy way to search/display archived events is important and we want to capture it.

**Comment by vsoch** [comment]
I just didn't add that check yet, should be possible with a few lines of jekyll :)

**Comment by vsoch** [comment]
I just tested this out - for the time being we really can't filter to expired events because the page would be entirely empty (we don't have any events!) so I'm just including the top 5 in each category, and the user can then navigate to the fill listing (still organized by category) or organized by year.
